language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
    - composer install --dev
    - composer require satooshi/php-coveralls 0.6.*

 after_script:
   - php vendor/bin/coveralls -v
